### ISSUE TITLE
minor issues fixed in 03-rstudio-and-code

### ISSUE THREAD

**Issue by xavidp** [PPBDS/r4ds.tutorials#33]
Hi, I've invested some time having a look at tutorial 03-rstudio-and-code, and fixed a couple of minor issues.
https://github.com/PPBDS/r4ds.tutorials/pull/32/commits/7005131a1a3205ea7713ba2642e8a453a7d8c868

I'm interested in translating this tutorial, since this is the next basic tutorial I kind-of need for my planned teaching tasks.
I've seen that it seems mostly finished until exercise 4 in quarto-2 section. It would be awesome to have it raised in your roadmap, if possible, so that I can also give it a go at translating whatever last part you end up writing/designing. You thought in some many details (to lower the learning curve) that I must admit that I  wouldn't have thought of if I was the one to design such awesome material.

Otherwise, no worries, what is mostly finished already is the basic part I expected/planned to include myself for people not Proficient in English (that need to dive into this world for work).

Therefore, congrats again for the nice work you are all doing, it's awesome! (I don't have to design all that, just translate it: gorgeous! :-D )

**Comment by davidkane9** [comment]
Thanks! Let me take a look.

**Comment by davidkane9** [comment]
Thanks for pointing this out!

1) I have pushed a better version, splitting out the Quarto part into four sections. I think it works better.

2) If there are other tutorials that you want me to clean up before you translate, please let me know.

3) I hope to submit this to CRAN by the end of the summer. One thing to be aware of is that CRAN has strict size limits, which we currently breach because of all the gifs in this tutorial, and in some others. I am not sure what is to be done, but I will keep you posted if changes are required.

**Comment by xavidp** [comment]
```
2. If there are other tutorials that you want me to clean up before you translate, please let me know.
```
I feel that I need to add in my teaching course some tutorial in Spanish about data import and export. That seems to be covered in 08-data-import. 

*Is it kinda finished?*

**Comment by davidkane9** [comment]
Yes

**Comment by xavidp** [comment]
Thanks, Dave, I'll continue then with the translation of that one.
